version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vanhackchallenge
      - MYSQL_DATABASE=vanhack_shortener
  app:
    build: .
    container_name: vanhackshortner
    links:
      - db
    depends_on:
      - db