version: '3.3'
volumes:
  data:
services:
  db:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vanhackchallenge
      - MYSQL_DATABASE=vanhack_shortener
    networks:
      - spring-boot-network

  app:
    container_name: vanhack-shortener
    build:
      context: .
      dockerfile: Dockerfile
    image: vithinholm/vanhackshortener:latest
    expose:
      - 8080
    networks:
      - spring-boot-network
    links:
      - db:mysql8
    ports:
      - 80:8080
    depends_on:
      - db

networks:
  spring-boot-network:
    driver: bridge

